# Generated by Django 4.1.5 on 2023-01-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], default=False, max_length=1),
        ),
    ]
