# Generated by Django 4.1.5 on 2023-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='periodo',
            field=models.CharField(choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período')], default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1),
        ),
    ]
