# Generated by Django 4.1.5 on 2023-01-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_periodo_competicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da modalidade')),
                ('genero_modalidade', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9)),
                ('competicao1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.competicao')),
            ],
        ),
    ]
