# Generated by Django 4.1.6 on 2023-02-05 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='profile'),
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Equipe')),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1)),
                ('periodo', models.CharField(choices=[('1', '1º Período'), ('2', '2º Período'), ('3', '3º Período'), ('4', '4º Período')], max_length=1)),
                ('curso_equipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
                ('modalidade_equipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.modalidade')),
                ('participantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
