# Generated by Django 4.1.6 on 2023-02-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_image_equipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipes',
        ),
    ]
